# Project identification
sonar.projectKey=project
sonar.projectName=project
sonar.projectVersion=1.0

# Connection details
sonar.host.url=http://localhost:9000
sonar.token=1234

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Paths to source directories and test files
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Exclusions
sonar.exclusions=**/*.spec.ts, **/node_modules/**, **/dist/**, **/e2e/**

# Path to coverage report
sonar.typescript.lcov.reportPaths=coverage/<your-project-name>/lcov.info